#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# The action scope of IoTDB Operator
# cluster: IoTDB Operator will watch and reconcile all iotdb resources in the whole Kubernetes cluster.
# namespace: IoTDB Operator will watch and reconcile iotdb resources in the specific namespace where Operator itself running in.
scope: "cluster"

# The Kubernetes namespace in which the IoTDB Operator will be installed.
# We strongly recommend that you should always set the namespace param, if not, the default namespace will be used.
namespace: "a"

# The iotdb-operator image and its version
image: "iotdb-operator:latest"

# If pulling from private docker registry, you should set the secret of the registry, it not set, images pulling will be failed for insufficient privileges.
# You can run the following command to create a secret and set secret name to `imagePullSecret`
#  "kubectl create secret docker-registry <secret_name> --namespace=<namespace> --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-password>"
imagePullSecret: ""

# The resource limitation for IoTDB Operator. Generally, the operator does not need too much resources.
# The default values could deal with the majority of scenarios.
cpu: 2
# The unit of memory is Mb
memory: 4096
