#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# In which kubernetes namespace lemming will run, if not set, use default namespace
namespace: "monitor"

# Port configurations
# All ports below will override its corresponding config in iotdb-xxx.properties
port: 9090

# For local test, you can just set serviceType to ClusterIP
serviceType: NodePort

# When serviceType is not NodePort or LoadBalancer, below configs will be ignored
# All xxxNodePort should be set in range from 30000 to 32767
nodePort: 30006

# The iotdb image version
#image: "zeus-acr-cn-beijing-1-registry.cn-beijing.cr.aliyuncs.com/lemming/prometheus:v2.29.1"
image: "bitnami/prometheus:2.34.0"

# The imagePullPolicy, should be one of IfNotPresent, Always, Never
imagePullPolicy: IfNotPresent

# If pulling from private docker registry, you should set the secret of the registry.
# You can run the following command to get the final secret string
#  "kubectl create secret docker-registry regsecret --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --dry-run -o yaml"
#imagePullSecrets: ""

# The resource limitation for each pod
cpu: 4
memory: 8Gi
disk: 100Gi

# The storageClassName for PersistenceVolume, it depends on your kubernetes provisioner
# If not set, you should create pvs for iotdb manually, more detail about pv see:
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
storageClassName: alicloud-disk-ssd
